#Remember this is the Github Desktop file, NOT the rpy one!
define p = Character("Player", color="#860000")
define alt = Character("Alternate Player", color="#810000")
default snack_choice = None

label start:

    play music "deskbgm.ogg"
    scene desk

    "You're sitting at your desk."
    "Your Monster is half empty."
    "Yet you take another sip."
    "Your project isn't going to finish itself."
    "You take a deep sigh."
    "You glance at the clock."
    "2:40 AM."
    "You have class in 5 hours."
    "You sigh again, and take another sip of your Monster."
    play sound "almost_done.ogg"
    "'Almost done.' You mutter to yourself."
    "You glance at the clock again."
    "2:41 AM."
    "Your typing speed is slow, like how your brain is functioning right now."
    "But you're pushing through."
    "This is important, your future depends on this project."
    "'Just keep going' you tell yourself."
    "You left your friends behind to work on this project."
    "Simply stopped replying to their messages."
    "You love them.. but school is hell right now."
    "You need to focus."
    "Focus on your project."
    "On your Future."
    "focus."
    "Focus."
    "Why can't you focus?"
    "."
    "."
    "."
    "You can't work like this."
    "You grab your now empty can of Monster, and leave your room."

    scene kitchen

    "You walk down the hall, and into the kitchen."
    "You open the fridge, and grab another can of Monster, practically ice cold this time."
    "The glow of the fridge on your face is bright.."
    "You squint your eyes and close the door."
    "Reaching up to the cabinet, you open it for any snacks."
    play sound "cabinetopen.ogg"
    "Cosmic Brownies.."
    "Or.. "
    "you reach further in the back of the cabinet."
    "Honey buns.."
    menu:
        "Cosmic Brownies":
            "You grab one of the cosmic brownies.."
            "These were always your favorite treat"
            "It's not a full meal but.."
            "Well.. a full meal doesn't sound too bad actually.."
            "Maybe I can order something.."
            "You close the cabinet door, and bring your snacks back to your bedroom."
            $ snack_choice = "Cosmic Brownies"

        "Honey buns":
            "You grab one of the honey buns.."
            "These are a bit more filling than the cosmic brownies would have been..."
            "You close the cabinet door, and bring your snacks back to your bedroom."
            $ snack_choice = "Honey buns"

    "Sighing, you sit back down at your desk."
    "You check the clock once more.."
    "3:00 AM."
    "'what?'"
    "'the fuck?'"
    "You glance at your Monster, and see that it's empty."
    "'But I just-'"
    "You glance at the clock again."
    "2:44 AM."
    if snack_choice == "Cosmic Brownies":
        jump food_order
    else:
        jump back_to_work

#YAY! FIRST BIG BREAKING POINT IN THE CODE~
label food_order:
    "I'm hungry.."
    "You pick up your phone to order some food."
    "Should.. I order.. or go to the store..?" #Super secret (not rlly) secret "Escape" option? maybe? idk
    menu:
        "Order food":
            "You decide to order some pizza and wings."
            "The little app on your phone says it's being prepared."
            jump wait_for_food
        "Go to the store":
            jump store_run

label wait_for_food:
    "You decide to check the clock one more time before going back to work."
    "2:46 AM"
    "'Ah fuck this.' And back to work you go."
    "You hear something on the carpet approaching your room.."
    "Like someone's walking towards it.."
    "'Mom..?'"
    "You call out to your mom, but she doesn't respond."
    "Probably because she's not supposed to be home"
    "You hear the sound of the door creaking open.."
    "your husky, Winter is standing in the doorway, looking at you."
    "'Jesus Winter! You can't just do that!'"
    "Winter tilts her head at you, like she's confused."
    "You sigh again, and reach into the box of treats by your desk."
    "'Why are you even awake?'"
    "You hand the treat to Winter, and give her very generous rubs."
    "She always seems to know when something's wrong~"
    "Then.."
    play sound "phone_ringing.ogg"
    "."
    "."
    "."
    "Unknown number."
    $ call_choice = renpy.call_screen("phone_call")

    if call_choice == "answer":
        stop sound "phone_ringing.ogg"
        "You answer the phone."
        a "Aaliyah?"
        p "Who is this?"
        a "Listen. I'm you."
        p "ex-excuse me?"
        a "Do NOT let the time hit 3:00 AM."
        p "What do-"
        "The call disconnects."
        jump call_accepted

    elif f call_choice == "decline":
        stop sound "phone_ringing.ogg"
        "You decline the call."
        "The phone stops ringing."
        "You glance at the clock again."
        "2:47 AM"
        "'Just another spam caller..'"
        "'I need to focus.'"
        "You go back to work."
        jump call_declined

screen phone_call():
    timer 5.0 action Return("decline")

    vbox
        textbutton "Answer" action Return("answer")
        textbutton "Decline" action Return("decline")


label call_accepted:
    "You stare at your phone."
    "That was my voice."
    "."
    "."
    "."
    "'No.'"
    "'I'm just tired.'"
    "You set your phone back down."
    "You glance at the clock once again."
    "It's still 2:47."
    "'Yeah.. fuck this-'"
    "You go back to working on your project."
    "'I'm just fucking tired..' You mutter to yourself."
    "You click back onto your presentation."
    "You stare at the same slide you've been working on "
    "You reread the same sentence."
    "It still doesn't make sense."
    "You blink."
    "Your read it again."
    " "
    "You finally make a few changes."
    "Delete."
    "Type."
    "Delete."
    "Type."

    "2:48 AM."

    "You sigh."
    "'Okay'"
    "'One more slide.'"
    "'Should.. I..'"

    menu:
        "Keep working":
            jump keep_working

        "Check the call:":
            jump check_call

        "Get some water":
            jump get_water

label keep_working:
    "You shake your head."
    "'Nope.'"
    "'Not dealing with that right now.'"

    "You turn back toward your computer."
    "Your presentation is still open."

    "You stare at the screen. "
    "The same slide has been sitting there for what feels like forever."

    "You move your mouse."
    "Click."
    "Type."
    "Delete."
    "Type again."

    "Slowly, the slide starts to come together."

    "You glance at the clock."

    "2:48 AM."

    "'Okay.'"
    "'That's better.'"

    "You take another sip of your Monster.."
    "Then look back at your presentation."

    "."
    "."
    "."

    "Something feels wrong."
    "You look at the clock again."
    "2:48 AM."
    "'What?'"
    "You wait a few seconds."
    "2:48 AM."
    "You refresh the clock."
    "2:48 AM."
    "."
    "."
    "."
    "You lean closer to the clock."
    "2:48 AM."
    "You check your computer."
    "2:48 AM."
    "You check your phone."
    "2:48 AM."
    "All three clocks agree."
    "'Okay...'"
    "'That's weird.'"
    "You look back at your presentation."
    "You start typing again."
    "A few sentences."
    "Then a paragraph."
    "You're finally getting somewhere."
    "You glance at the clock."
    "2:49 AM."
    "You sigh in relief."
    "'See?'"
    "'I'm just tired.'"
    "You continue working."
    "."
    "."
    "."
    play sound "notification.ogg"
    "You hear a notification."
    "No new messages."
    "You frown."
    play sound "notification.ogg"
    "The notification sound plays again."
    "Still nothing."
    "You check the clock."
    "2:48 AM."
    "You stare at the clock."
    "2:48 AM."
    "You look at your phone again."
    "Nothing."
    "."
    "."
    "."
    "okay..."
    "You put your phone back down."
    "A few seconds pass."
    play sound "notification.ogg"
    "You freeze."
    "You slowly look at your phone."
    "Nothing."
    "You pick it up."
    "No notifications."
    "You check your messages."
    "Nothing."
    "You check your email."
    "Nothing."
    "You open your presentation again."
    "."
    "."
    "."
    "There's a new slide."
    "Slide 13 of 12."
    "'What the fuck?'"
    "You click on the slide."
    "Don't let it reach 3."
    "That is all the slide reads."
    "You stare at the slide."
    "."
    "."
    "."
    "'I didn't make this.'"
    "You look at the rest of the presentation."
    "Every other slide is exactly how you remember it."
    "You click back to slide 12."
    "Slide 12 of 12."
    "You click forward."
    "Slide 13 of 12."
    "Don't let it reach 3."
    "'Okay.'"
    "You close the presentation."
    "'Nope.'"
    "You reopen the presentation."
    "Slide 13 is still there."
    "You select it."
    "Delete."
    "The slide disappears."
    "You sigh."
    "'Finally.'"
    "You look at the clock."
    "2:49 AM."
    "You turn back to your computer."
    "slide 13 of 12."
    "It's back."
    menu:
        "Delete the slide":
            jump delete_slide
        "Read the slide again":
            jump read_slide
        "Close the presentation":
            jump close_presentation
        "Call the number back":
            jump call_back

label delete_slide:
    "You stare at the slide."
    "'Nope.'"
    "You click the slide."
    "You select everything."
    "Delete."
    "The slide disappears."
    "You stare at the presentation."
    "Slide 12 of 12."
    "'okay.'"
    "You lean back in your chair."
    "You let out a long sigh."
    "'I'm seriously losing it.'"
    "You take another sip of your Monster."
    "You turn back toward your computer."
    "."
    "."
    "."
    "You hear a faint clicking sound."
    "Click."
    "Click."
    "Click."
    "You look at your computer."
    "Slide 13 of 12."
    "You freeze."
    "'No.'"
    "You click on the slide."
    "Don't let it reach 3."
    "You didn't type it."
    "You didn't copy it."
    "You deleted it."
    "And yet..."
    "It's still there."
    menu:
        "Delete it again":
            jump delete_again
        "Leave it alone":
            jump leave_slide
        "Take a picture of it.":
            jump take_picture
        "Close your laptop":
            jump close_laptop

label delete_again:
    "You stare at the slide."
    "'No.'"
    "You select it again."
    "Delete."
    "The slide disappears."
    "You wait."
    "Nothing happens."
    "'...Okay.'"
    "You lean back in your chair."
    "You look at the clock."
    "2:49 AM."
    "You let out a shaky breath."
    "'It's gone.'"
    "You turn at it for a moment."
    "Then you start typing."
    "Click."
    "Type."
    "Delete."
    "Type again."
    "You glance at the clock."
    "2:49 AM."
    "You continue working."
    "."
    "."
    "."
    "Click."
    "Type."
    "Delete."
    "You glance at the clock again."
    "2:49 AM."
    "'Why isn't it moving?'"
    "You look at your phone."
    "2:49 AM."
    "You look at your computer."
    "2:49 AM."
    "You look at the clock."
    "2:49AM."
    "You wait."
    "Nothing."
    "You keep working."
    "You don't notice the clock change."
    "You don't notice the room getting darker."
    "You don't notice your computer screen flicker."
    "Until you hear it."
    play sound "notification.ogg"
    "You look down."
    "A new slide has appeared."
    "Slide 13 of 12."
    "You freeze."
    "The words are different this time."
    "'You already tried this.'"
    "."
    "."
    "."
    "The clock changes."
    "2:50 AM."
    "You stare at the screen."
    "."
    "."
    "."
    "'..What?'"
    "Your computer goes black."
    "You look at your reflection in the screen."
    "She's staring back at you."
    "But she's smiling."
    "You don't remember smiling."
    play sound "phone_ringing.ogg"
    "You hear your phone ringing."
    "Unknown number."
    "You don't answer."
    stop sound "phone_ringing.ogg"
    "The ringing stops."
    "."
    "."
    "."
    play sound "phone_ringing.ogg"
    "Then it starts again."
    "You look at the clock."
    "2:50 AM"
    "You realize something."
    "The clock isn't counting forward."
    "It's counting down."
    "2:49."
    "2:48."
    "2:47."
    "You stare at the numbers."
    "'No.'"
    "2:46."
    "2:45."
    "2:44."
    "You reach for your phone."
    "The screen goes black."
    "."
    "."
    "."
    "3:00 AM."

    scene black
    "ENDING #1"
    "COUNTDOWN"
    "You tried to erase it."
    "But some things aren't meant to be deleted."
    "CODE: 24913"
    return


label leave_slide:
    "You stare at the slide."
    "Don't let it reach 3."
    "."
    "."
    "."
    "'Whatever.'"
    "You close the slide."
    "You don't delete it."
    "You don't read it again"
    "You don't want to think about it."
    "You just want to finish your presentation."
    "You click on slide 12."
    "You start working again."
    "Click."
    "Type."
    "Delete."
    "Type again."
    "Slowly, you lose yourself in the work."
    "For a while, everything feels normal."
    "You glance at the clock."
    "2:50 AM."
    "'See?'"
    "'Nothing happened.'"
    "You turn back to your computer."
    "You keep working."
    "."
    "."
    "."
    "A few minutes pass."
    "You glance at the clock again."
    "2:50 AM."
    "You frown."
    "'Didn't it just say that?'"
    "You shake your head."
    "'I'm tired.'"
    "You keep typing."
    "Click."
    "Type."
    "Delete."
    "Type again."
    "You glance at the clock."
    "2:50 AM."
    "You stop typing."
    "."
    "."
    "."
    "You look at the presentation."
    "Slide 12 of 12."
    "'Okay.'"
    "Everything is normal."
    "You smile faintly."
    "'I'm fine.'"
    "You look back at the clock."
    "2:50 AM."
    "You don't notice the thirteenth slide."
    "You don't notice it slowly opening."
    "You don't notice the words appearing."
    "Don't let it hit 3."
    "You continue working."
    "."
    "."
    "."
    "2:51 AM."
    "You finally look up."
    "The clock says 2:51."
    "'Oh.'"
    "You sigh in relief."
    "'Finally.'"
    "You look back at your computer."
    "Slide 13 of 12."
    "You stare at it."
    "The words have changed."
    "You should have listened."
    "Your smile disappears."
    "The screen goes black."
    "."
    "."
    "."
    "3:00 AM."
    jump ending_02

label ending_02:
    scene black
    "ENDING #2"
    "DENIAL"
    "You ignored the warning."
    "The warning didn't ignore you."
    "CODE: 25013"
    return


label take_picture:
    "You stare at the slide."
    "Don't let it reach 3."
    "You reach for your phone."
    "'Okay.'"
    "You open the camera."
    "You point it at the screen."
    "The camera focuses."
    "Slide 13 of 12."
    "You hesitate."
    "'This is gonna sound so stupid.'"
    "You take the picture."
    play sound "camera_shutter.ogg"
    "The screen flashes."
    "You lower your phone."
    "You look at the picture."
    "Slide 13 of 12."
    "'Okay.'"
    "You zoom in."
    "The text is still there."
    "You zoom out."
    "Everything looks normal."
    "Your presentation."
    "Your desk."
    "Your computer."
    "Your room."
    "You glance back at the actual screen."
    "Slide 13 of 12."
    "'So... It's real.'"
    "You look at the picture again."
    "Something catches your eye."
    "You zoom in."
    "The clock."
    "2:50 AM"
    "You look back at your phone."
    "2:50 AM."
    "'Huh.'"
    "You put your phone down."
    "You stare at the presentation."
    "Maybe taking a picture wasn't such a bad idea."
    "You pick your phone back up."
    "You open the picture again."
    "."
    "."
    "."
    "You freeze."
    "The clock in the picture says 2:51 AM."
    "You look at the clock on the wall."
    "2:50 AM."
    "'What?'"
    "You refresh the picture."
    "2:51 AM."
    "You look at the clock again."
    "2:50 AM."
    "You wait."
    "Nothing changes."
    "You look at the picture."
    "2:51 AM."
    "You zoom in further."
    "There is something else in the picture."
    "Something standing behind you."
    "You slowly turn around."
    "Nothing."
    "You look back at the picture."
    "It's still there."
    "You zoom in."
    "You can't make out a face."
    "Just a silhouette."
    play sound "camera_shutter.ogg"
    "You look at it."
    "The silhouette is gone."
    "You let out a breath."
    "'Okay.'"
    "You look at the first picture again."
    "The silhouette is still there."
    "You look at the second picture."
    "Nothing."
    "You compare the two."
    "Same room."
    "Same desk."
    "Same computer."
    "Same presentation."
    "Different time."
    "You look at the timestamps."
    "First picture: 2:50 AM."
    "Second picture: 2:51 AM."
    "You look at the clock."
    "2:50 AM."
    "."
    "."
    "."
    "'No.'"
    "You take another picture."
    play sound "camera_shutter.ogg"
    "You look at it."
    "2:52 AM."
    "Your hands go still."
    "You check the actual clock."
    "2:50 AM."
    "You check your phone's time."
    "2:50 AM."
    "You look at the presentation."
    "Slide 13 of 12"
    "The words have changed."
    "You didn't notice them change before."
    "Don't let it reach 3."
    "You stare at the screen."
    "'What happens at 3?'"
    "The cursor moves."
    "You aren't touching the mouse."
    "Click."
    "The presentation opens a new slide."
    "Slide 14 of 12."
    "You stop breathing."
    "The slide is blank."
    "Except for one sentence."
    "You shouldn't have taken the picture."
    play sound "notification.ogg"
    "Your phone buzzes."
    "You look down."
    "A new photo has appeared in your gallery."
    "You didn't take it."
    "You open it."
    "It's a picture of you."
    "Sitting at your desk."
    "Looking at your phone."
    "You stare at the picture."
    "The timestamp reads:"
    "3:00 AM."
    "You look at the clock."
    "2:50 AM."
    "You look back at the photo."
    "Something is written across the bottom."
    "RUN."
    "You drop your phone."
    "The screen goes black."
    "."
    "."
    "."
    play sound "camera_shutter.ogg"
    "You hear the camera shutter."
    "You slowly look down."
    "Your phone is still on the floor."
    "The camera is open."
    "The timer is counting down."
    "2:49."
    "2:48."
    "2:47."
    "You stare at the screen."
    "The numbers keep falling."
    "2:46."
    "2:45."
    "2:44."
    "You reach for your phone."
    "The screen flashes."
    "3:00 AM."
    jump ending_03

label ending_03:
    scene black
    "ENDING #3."
    "THE PHOTOGRAPH."
    "Some things are better left unseen."
    "CODE: 25113."
    return


label close_laptop:
    "You stare at the slide."
    "Don't let it reach 3."
    "You don't want to look at it anymore."
    "'Nope.'"
    "You close your laptop."
    "The screen disappears."
    "You lean back in your chair."
    "Silence."
    "You let out a long breath."
    "'Okay.'"
    "'That's enough.'"
    "You look at the clock."
    "2:51 AM."
    "'I'm going to bed.'"
    "You stand up."
    "You stretch."
    "Your room feels strangely quiet."
    "You look back at your laptop."
    "It's still closed."
    "Good."
    "You turn away."
    "Click."
    "You freeze."
    "The sound came from behind you."
    "You slowly turn around."
    "Your laptop is still closed."
    "."
    "."
    "."
    "Click."
    "Click."
    "Click."
    "You stare at it."
    "'No.'"
    "You take a step backward."
    "The clicking stops."
    "You wait."
    "Nothing."
    "You shake your head."
    "'I'm tired.'"
    "You walk toward your bedroom door."
    "Your hand reaches for the handle."
    "Click."
    "You stop."
    "This time, the sound comes from inside the laptop."
    "You turn around."
    "The laptop is still closed."
    "But the charging light is on."
    "You didn't plug it in."
    "You stare at the light."
    "It flickers."
    "Once."
    "Twice."
    "Three times."
    "You hear a faint hum."
    "You step closer."
    "The screen turns of."
    "You never opened it."
    "The laptop displays one thing."
    "Slide 13 of 12."
    "You stare as it."
    "'I closed you.'"
    "The cursor moves."
    "Click."
    "A new slide appears."
    "Slide 14 of 12."
    "You take another step backward."
    "The screen goes black."
    "For a moment, you see your reflection."
    "Then the reflection moves."
    "You don't."
    "You freeze."
    "Your reflection slowly raises its hand."
    "You stare at it."
    "It points toward the clock."
    "2:52 AM."
    "You turn toward the clock."
    "Then back toward the laptop."
    "Your reflection is gone."
    "The laptop screen is normal."
    "Slide 12 of 12."
    "You stare at it."
    "Nothing is wrong."
    "."
    "."
    "."
    "'Okay.'"
    "You close the laptop again."
    "This time, it stays closed."
    "You walk out of your room."
    "You don't look back."
    "You close the door behind you."
    "Silence."
    "You walk down the hallway."
    "One step."
    "Two steps."
    "Three."
    "You stop."
    "You hear your laptop open."
    "From inside your room."
    "You slowly turn around."
    "The door is still closed."
    "You hear typing."
    "Click."
    "Type."
    "Delete."
    "Type."
    "You stare at the door."
    "The typing stops."
    play sound "notification.ogg"
    "Your phone buzzes."
    "You look down."
    "A notification."
    "No new messages."
    "You lock your phone."
    play sound "notification.ogg"
    "No new messages."
    "You look at the time."
    "2:53 AM."
    "You sigh."
    "'I'm going to sleep.'"
    "You walk away."
    "Behind you, your bedroom door slowly opens."
    "You don't notice."
    "The laptop screen glows in the dark."
    "Slide 13 of 12."
    "The warning is gone."
    "A new sentence appears."
    "Thank you for leaving."
    jump ending_04

label ending_04:
    scene black
    "ENDING #4"
    "THE EXIT"
    "You left the room."
    "Something else left with you."
    "CODE: 00000"
    return

label read_slide:

label close_presentation:

label call_back:


label check_call:



label get_water:



#DECLINED PATH (for the sake of my organization)
label call_declined








label store_run:
    "TBD!"

label back_to_work:
    "Welcome to where this doesn't work yet."
    "Sorry, not sorry! heh"

    return